
[runtime]
log_level="WARNING" 
dlthub_telemetry = true
export_schema_path="schemas/export"
import_schema_path="schemas/import"

origin_url = "https://d37ci6vzurychx.cloudfront.net/trip-data"
logs_path = ".logs/nyc_taxi.log"
pipeline_name = "nyc_taxi"
dataset_name = "nyc_taxi_data"
destination = "bigquery"

[data_writer]
buffer_max_items = 100000  
file_max_bytes = 50000000  

[normalize]
workers = 5 
pool_type = "process"

[load]
workers = 12 